CREATE DATABASE quaiavare;
USE quaiavare ;
CREATE TABLE users (
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
name TEXT(100) NOT NULL,
email VARCHAR(100) NOT NULL UNIQUE,
password VARCHAR(100) NOT NULL,
inscription_date DATETIME DEFAULT CURRENT_TIMESTAMP, 
is_admin BOOLEAN NOT NULL DEFAULT FALSE,
allergy TEXT(255)
);



CREATE TABLE reservations (
id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(255) NOT NULL,
date DATE NOT NULL,
hour TIME NOT NULL,
count INT UNSIGNED NOT NULL
);




